# -*- coding: utf-8 -*-
"""step3_make_splits_dev_holdoutH.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZSD-IHirkzs8h6IwF07NzqWNaGz0Jx9
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Étape 3 — Splits DEV / HOLDOUT-H (BMO)
Entrée  : episodes_with_silver.jsonl (Étape 2)
Sorties :
  - /content/drive/MyDrive/splits_bmo/episodes_dev.jsonl
  - /content/drive/MyDrive/splits_bmo/episodes_holdoutH.jsonl
  - /content/drive/MyDrive/splits_bmo/splits.csv
"""

import os, json, csv, random
from collections import Counter

# ========= CHEMINS À ADAPTER SI BESOIN =========
IN_JSONL = "/content/drive/MyDrive/cleansilver_bmo/episodes_with_silver.jsonl"
OUT_DIR  = "/content/drive/MyDrive/splits_bmo"
# =============================================

DEV_RATIO = 0.785   # ~157/200 pour BMO
SEED      = 2025
random.seed(SEED)

def ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def load_cards(path: str):
    cards = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                cards.append(obj)
            except Exception:
                continue
    return cards

def main():
    ensure_dir(OUT_DIR)

    cards = load_cards(IN_JSONL)
    n = len(cards)
    if n == 0:
        print("[ERR] Aucun épisode lu dans", IN_JSONL)
        return

    # id d’épisode pour traçabilité
    def eid(c):
        return str(c.get("key") or c.get("ticket_id") or "")

    # mélange déterministe
    idx = list(range(n))
    random.shuffle(idx)

    dev_count = int(round(DEV_RATIO * n))
    dev_idx   = set(idx[:dev_count])
    h_idx     = set(idx[dev_count:])

    out_dev_path = os.path.join(OUT_DIR, "episodes_dev.jsonl")
    out_h_path   = os.path.join(OUT_DIR, "episodes_holdoutH.jsonl")
    splits_csv   = os.path.join(OUT_DIR, "splits.csv")

    # stats de labels
    dist_all = Counter()
    dist_dev = Counter()
    dist_h   = Counter()

    with open(out_dev_path, "w", encoding="utf-8") as f_dev, \
         open(out_h_path,   "w", encoding="utf-8") as f_h, \
         open(splits_csv,   "w", newline="", encoding="utf-8") as f_csv:

        cw = csv.writer(f_csv)
        cw.writerow(["episode_id", "split"])

        for i, c in enumerate(cards):
            lab = c.get("_silver_label") or "NONE"
            dist_all[lab] += 1

            if i in dev_idx:
                f_dev.write(json.dumps(c, ensure_ascii=False) + "\n")
                dist_dev[lab] += 1
                cw.writerow([eid(c), "DEV"])
            else:
                f_h.write(json.dumps(c, ensure_ascii=False) + "\n")
                dist_h[lab] += 1
                cw.writerow([eid(c), "H"])

    print(f"[SPLIT] total: {n} | DEV: {len(dev_idx)} | HOLDOUT-H: {len(h_idx)}")
    print("[SPLIT] label dist (ALL):", dict(dist_all))
    print("[SPLIT] label dist (DEV):", dict(dist_dev))
    print("[SPLIT] label dist (H  ):", dict(dist_h))
    print("- DEV       :", out_dev_path)
    print("- HOLDOUT-H :", out_h_path)
    print("- SPLITS    :", splits_csv)

if __name__ == "__main__":
    main()